import type { Patient, Appointment, DailyStats } from "@/types";

export const mockPatients: Patient[] = [
  {
    id: "P-001",
    name: "Sarah Mitchell",
    dob: "1985-03-14",
    age: 40,
    phone: "(555) 204-8821",
    email: "sarah.mitchell@email.com",
    insurance: "BlueCross BlueShield",
    insuranceId: "BCB-88221-X",
    lastVisit: "2025-09-15",
    nextAppointment: "2026-03-16",
    outstandingBalance: 0,
    medicalAlerts: [
      { type: "allergy", label: "Penicillin Allergy", severity: "high" },
      { type: "condition", label: "Hypertension", severity: "medium" },
    ],
    teeth: [
      { toothNumber: 3, condition: "crown", notes: "PFM crown placed 2023", lastUpdated: "2023-06-01" },
      { toothNumber: 14, condition: "filling", notes: "Composite resin", lastUpdated: "2024-02-10" },
      { toothNumber: 19, condition: "root-canal", notes: "RCT completed, build-up done", lastUpdated: "2022-11-20" },
      { toothNumber: 30, condition: "cavity", notes: "Interproximal, needs restoration", lastUpdated: "2025-09-15" },
    ],
    notes: "Patient is anxious. Premedicate with nitrous. Preferred morning appointments.",
    provider: "Dr. Emily Chen",
  },
  {
    id: "P-002",
    name: "James Thornton",
    dob: "1972-07-29",
    age: 53,
    phone: "(555) 317-9045",
    email: "j.thornton@workmail.com",
    insurance: "Delta Dental PPO",
    insuranceId: "DD-44190-T",
    lastVisit: "2026-01-08",
    outstandingBalance: 340.0,
    medicalAlerts: [
      { type: "medication", label: "Blood Thinner: Warfarin", severity: "high" },
      { type: "condition", label: "Type 2 Diabetes", severity: "medium" },
    ],
    teeth: [
      { toothNumber: 2, condition: "missing", notes: "Extracted 2019, implant planned", lastUpdated: "2019-05-01" },
      { toothNumber: 15, condition: "crown", notes: "E-Max crown", lastUpdated: "2024-08-14" },
      { toothNumber: 18, condition: "missing", notes: "Extracted 2020", lastUpdated: "2020-03-10" },
      { toothNumber: 31, condition: "filling", notes: "Amalgam, watch for fracture", lastUpdated: "2023-01-05" },
    ],
    notes: "Check INR before any surgical procedure. Coordinate with PCP Dr. Brooks.",
    provider: "Dr. Marcus Reid",
  },
  {
    id: "P-003",
    name: "Priya Anand",
    dob: "1995-11-02",
    age: 30,
    phone: "(555) 482-6630",
    email: "priya.anand@gmail.com",
    insurance: "Aetna Dental",
    insuranceId: "AET-30192-A",
    lastVisit: "2025-12-20",
    nextAppointment: "2026-03-16",
    outstandingBalance: 75.0,
    medicalAlerts: [],
    teeth: [
      { toothNumber: 1, condition: "missing", notes: "Wisdom tooth never erupted", lastUpdated: "2021-01-01" },
      { toothNumber: 16, condition: "missing", notes: "Wisdom tooth never erupted", lastUpdated: "2021-01-01" },
      { toothNumber: 17, condition: "missing", notes: "Wisdom tooth never erupted", lastUpdated: "2021-01-01" },
      { toothNumber: 32, condition: "missing", notes: "Wisdom tooth never erupted", lastUpdated: "2021-01-01" },
    ],
    notes: "Orthodontic retainer wearer. Check for any shifting.",
    provider: "Dr. Emily Chen",
  },
  {
    id: "P-004",
    name: "Robert Kim",
    dob: "1960-05-18",
    age: 65,
    phone: "(555) 601-7714",
    email: "rkim@outlook.com",
    insurance: "Medicare Advantage",
    insuranceId: "MCR-65901-K",
    lastVisit: "2025-11-10",
    nextAppointment: "2026-03-16",
    outstandingBalance: 1250.0,
    medicalAlerts: [
      { type: "allergy", label: "Latex Allergy", severity: "high" },
      { type: "medication", label: "Bisphosphonate: Fosamax", severity: "high" },
      { type: "condition", label: "Osteoporosis", severity: "medium" },
    ],
    teeth: [
      { toothNumber: 3, condition: "crown", lastUpdated: "2021-03-01" },
      { toothNumber: 5, condition: "implant", notes: "Nobel Biocare, osseointegration confirmed", lastUpdated: "2023-09-01" },
      { toothNumber: 12, condition: "crown", lastUpdated: "2022-07-15" },
      { toothNumber: 19, condition: "crown", lastUpdated: "2020-11-30" },
      { toothNumber: 20, condition: "filling", lastUpdated: "2024-01-20" },
      { toothNumber: 28, condition: "root-canal", notes: "Completed, crown needed", lastUpdated: "2025-11-10" },
      { toothNumber: 29, condition: "cavity", notes: "Class II, schedule restoration", lastUpdated: "2025-11-10" },
    ],
    notes: "LATEX FREE PROTOCOL. Bisphosphonate risk — no extractions without MD clearance. Full mouth needs comprehensive treatment plan.",
    provider: "Dr. Marcus Reid",
  },
  {
    id: "P-005",
    name: "Olivia Garza",
    dob: "2008-09-30",
    age: 17,
    phone: "(555) 773-2258",
    email: "garza.family@gmail.com",
    insurance: "Cigna Dental",
    insuranceId: "CIG-17008-G",
    lastVisit: "2026-02-01",
    nextAppointment: "2026-03-16",
    outstandingBalance: 0,
    medicalAlerts: [
      { type: "warning", label: "Minor — Guardian Consent Required", severity: "medium" },
    ],
    teeth: [
      { toothNumber: 1, condition: "missing", notes: "Wisdom, not yet erupted", lastUpdated: "2026-02-01" },
      { toothNumber: 16, condition: "missing", notes: "Wisdom, not yet erupted", lastUpdated: "2026-02-01" },
      { toothNumber: 17, condition: "missing", notes: "Wisdom, not yet erupted", lastUpdated: "2026-02-01" },
      { toothNumber: 32, condition: "missing", notes: "Wisdom, not yet erupted", lastUpdated: "2026-02-01" },
      { toothNumber: 14, condition: "filling", notes: "Sealant + composite", lastUpdated: "2025-08-15" },
      { toothNumber: 19, condition: "filling", notes: "Sealant + composite", lastUpdated: "2025-08-15" },
    ],
    notes: "Orthodontic patient (braces). Coordinating with Dr. Park at Bright Smiles Ortho.",
    provider: "Dr. Emily Chen",
  },
  {
    id: "P-006",
    name: "David Okonkwo",
    dob: "1988-01-11",
    age: 38,
    phone: "(555) 894-4471",
    email: "d.okonkwo@protonmail.com",
    insurance: "United Concordia",
    insuranceId: "UC-38881-O",
    lastVisit: "2025-06-22",
    outstandingBalance: 0,
    medicalAlerts: [],
    teeth: [
      { toothNumber: 8, condition: "crown", notes: "Veneer, cosmetic", lastUpdated: "2024-05-10" },
      { toothNumber: 9, condition: "crown", notes: "Veneer, cosmetic", lastUpdated: "2024-05-10" },
    ],
    notes: "Excellent oral hygiene. Interested in whitening touch-up.",
    provider: "Dr. Emily Chen",
  },
];

// Today's appointments — March 16, 2026
export const todaysAppointments: Appointment[] = [
  {
    id: "A-001",
    patientId: "P-001",
    patientName: "Sarah Mitchell",
    time: "08:00",
    duration: 60,
    type: "crown",
    chair: "Chair 1",
    status: "completed",
    provider: "Dr. Emily Chen",
    notes: "Crown seat #30, post root canal",
  },
  {
    id: "A-002",
    patientId: "P-003",
    patientName: "Priya Anand",
    time: "09:00",
    duration: 45,
    type: "cleaning",
    chair: "Hygienist",
    status: "in-chair",
    provider: "Hygienist Lena Park",
  },
  {
    id: "A-003",
    patientId: "P-006",
    patientName: "David Okonkwo",
    time: "09:30",
    duration: 30,
    type: "consultation",
    chair: "Chair 2",
    status: "checked-in",
    provider: "Dr. Emily Chen",
    notes: "Whitening consultation",
  },
  {
    id: "A-004",
    patientId: "P-002",
    patientName: "James Thornton",
    time: "10:00",
    duration: 90,
    type: "crown",
    chair: "Chair 1",
    status: "confirmed",
    provider: "Dr. Marcus Reid",
    notes: "Crown prep #28. Verify INR lab results before procedure.",
  },
  {
    id: "A-005",
    patientId: "P-005",
    patientName: "Olivia Garza",
    time: "10:30",
    duration: 60,
    type: "exam",
    chair: "Hygienist",
    status: "confirmed",
    provider: "Hygienist Lena Park",
    notes: "Ortho check + cleaning. Guardian Maria Garza accompanies.",
  },
  {
    id: "A-006",
    patientId: "P-004",
    patientName: "Robert Kim",
    time: "11:30",
    duration: 90,
    type: "root-canal",
    chair: "Chair 1",
    status: "confirmed",
    provider: "Dr. Marcus Reid",
    notes: "RCT #29. LATEX FREE SETUP REQUIRED.",
  },
  {
    id: "A-007",
    patientId: "P-003",
    patientName: "Priya Anand",
    time: "13:00",
    duration: 60,
    type: "filling",
    chair: "Chair 2",
    status: "confirmed",
    provider: "Dr. Emily Chen",
  },
  {
    id: "A-008",
    patientId: "P-001",
    patientName: "Sarah Mitchell",
    time: "14:00",
    duration: 45,
    type: "exam",
    chair: "Hygienist",
    status: "confirmed",
    provider: "Hygienist Lena Park",
    notes: "6-month recall",
  },
  {
    id: "A-009",
    patientId: "P-006",
    patientName: "David Okonkwo",
    time: "15:00",
    duration: 60,
    type: "whitening",
    chair: "Chair 2",
    status: "confirmed",
    provider: "Dr. Emily Chen",
  },
];

export const dailyStats: DailyStats = {
  date: "2026-03-16",
  totalAppointments: 9,
  completedAppointments: 1,
  dailyRevenue: 4820,
  pendingLabCases: 3,
  newPatients: 1,
  cancellations: 0,
};

export const pendingLabCases = [
  { id: "LAB-001", patient: "James Thornton", item: "PFM Crown #15", lab: "Precision Dental Lab", due: "2026-03-18", status: "in-progress" },
  { id: "LAB-002", patient: "Robert Kim", item: "Zirconia Crown #28", lab: "Precision Dental Lab", due: "2026-03-19", status: "sent" },
  { id: "LAB-003", patient: "Sarah Mitchell", item: "Nightguard (full arch)", lab: "SmileTech Labs", due: "2026-03-20", status: "in-progress" },
];
